// Generated by CoffeeScript 1.11.1
var ReactComponent, ReactNativeComponentTree, ReactNativeEventEmitter, assertType, simulateNativeEvent;

ReactNativeComponentTree = require("ReactNativeComponentTree");

ReactNativeEventEmitter = require("ReactNativeEventEmitter");

ReactComponent = require("ReactComponent");

assertType = require("assertType");

simulateNativeEvent = function(target, registrationName, nativeEvent) {
  var topLevelType;
  if (target instanceof ReactComponent) {
    target = ReactNativeComponentTree.getNodeFromInstance(target);
  }
  assertType(target, Number);
  assertType(registrationName, String);
  assertType(nativeEvent, Object);
  if (ReactNativeEventEmitter.registrationNames[registrationName] == null) {
    throw Error("Invalid event name: " + registrationName);
  }
  topLevelType = registrationName.replace(/^on/, "top");
  nativeEvent = Object.assign({}, nativeEvent, {
    target: target
  });
  ReactNativeEventEmitter.receiveEvent(target, topLevelType, nativeEvent);
};

module.exports = simulateNativeEvent;
